#!/bin/bash

if [ -f "commit.txt" ]
then 
	`rm commit.txt`
fi
cp /mnt/hgfs/sharewl/commit.txt commit.txt

time=`date`
echo `date`>>commit.txt
echo "************************************">>commit.txt

echo `cat commit.txt`>>note.log
clear

if [ -f "note.c" ]
then
	`rm note.c`
fi
cp /mnt/hgfs/sharewl/note.c note.c
cp /mnt/hgfs/sharewl/note.h note.h
echo 1111111111111

make

if [ $? != 0 ]
then
	echo gcc failed
	exit 1
fi
echo 2222222222222

gcc main.c -L. -lnote -o main

`export LD_LIBRARY_PATH=.`
if [ $? != 0 ]
then
	echo export fail
	exit 1
fi

./main

git add note.c
git add note.h
git add cpt2
git add note.log
git commit -F commit.txt
