#!/bin/bash

clear

function addlog
{	
	rm commit.txt
	touch commit.txt
	
	read -p "修改人：" name
	echo "修改人：$name">>commit.txt
	
	read -p "修改原因：" reason
	echo "修改原因：$reason">>commit.txt
	
	
	read -p "目前缺陷：" bug
	echo "目前缺陷：$bug">>commit.txt
	
	echo `date`>>commit.txt
	echo "*****************************">>commit.txt
	
	echo `cat commit.txt`>>note.log
}


function makelib
{
	echo "编译时间为："`date`
	
	make

	if [ $? != 0 ]
	then
		echo gcc libnote failed
		exit 1
	fi
	echo "请输入文件名："

	gcc main.c -L. -lnote -o main.o
	
	if [ $? != 0 ]
	then
		echo gcc main.c fail
		exit 1
	fi
	
	export LD_LIBRARY_PATH=.
}

function commit
{
	git add note.c
	git add note.h
	git add noteb
	git add libnote.so
	git add main.c
	git add commit.txt
	git add note.log
	git add Makefile
	git add README.md
	git commit -F commit.txt
}


makelib

./main.o

echo -n "commit or not:y/n"
read ret
if [ $ret = y -o $ret = Y  ]
then
	addlog
	commit
fi

