#!/bin/bash

clear

function addlog
{
	#time=`date`
	rm commit.txt
	touch commit.txt
	echo "修改人："
	read name
	echo $name>>commit.txt
	echo "修改原因："
	read reason
	echo $reason>>commit.txt
	echo "目前缺陷："
	read bug
	echo $bug>>commit.txt
	echo "时间：" 
	echo `date`>>commit.txt
	echo "\n11111111111111111111">>commit.txt
	echo `cat commit.txt`>>note.log
}


function makelib
{
	echo "编译时间为："`date`
	
	make

	if [ $? != 0 ]
	then
		echo gcc failed
		exit 1
	fi
	echo "请输入文件名："

	gcc main.c -L. -lnote -o main.o
	
	if [ $? != 0 ]
	then
		echo export fail
		exit 1
	fi
	
	export LD_LIBRARY_PATH=.
}

function commit
{
	git add note.c
	git add note.h
	git add noteb
	git add libnote.so
	git add main.c
	git add note.log
	git add Makefile
	git add README.md
	git commit -F commit.txt
}


makelib

./main.o

echo "commit or not:y/n"
read ret
if [ $ret = y -o $ret = Y  ]
then
	addlog
	commit
fi

